# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentdash < Formula
  desc "w for your AI agents"
  homepage "https://github.com/yrstm/agentdash"
  version "2.3.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/yrstm/agentdash/releases/download/v2.3.0/agentdash-linux-amd64"
    sha256 "5ba791f20f62e470cc0e3468dfd4fd2436965d31a6b8c9837a649ab252d6f9f7"
    define_method(:install) do
      bin.install "agentdash-linux-amd64" => "agentdash"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/yrstm/agentdash/releases/download/v2.3.0/agentdash-linux-arm64"
    sha256 "bb22aa942fa58e561505aba2b1d79f9073c48670122cd1daffc3c2f31d18e1c5"
    define_method(:install) do
      bin.install "agentdash-linux-arm64" => "agentdash"
    end
  end
end
