# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentdash < Formula
  desc "w for your AI agents"
  homepage "https://github.com/yrstm/agentdash"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yrstm/agentdash/releases/download/v0.2.4/agentdash-darwin-amd64"
      sha256 "6346a3b9a5acc6f4d823fd7fcf0527895ffa6d51817f4fe62077f41fbe8d5e83"

      define_method(:install) do
        bin.install "agentdash-darwin-amd64" => "agentdash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yrstm/agentdash/releases/download/v0.2.4/agentdash-darwin-arm64"
      sha256 "5a056ecee017837863d268df52170dbe1ba91655c89d11d8a4b042b543a26f2e"

      define_method(:install) do
        bin.install "agentdash-darwin-arm64" => "agentdash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yrstm/agentdash/releases/download/v0.2.4/agentdash-linux-amd64"
      sha256 "1a1ab6cc3c7acd96ba239a7ce3c16d6e3fcc75eaecfae794e498c902e300ed29"
      define_method(:install) do
        bin.install "agentdash-linux-amd64" => "agentdash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yrstm/agentdash/releases/download/v0.2.4/agentdash-linux-arm64"
      sha256 "5b03d447657845b512f7842d24b1759140994ed788d56f41ffbc2ba4b05eb90d"
      define_method(:install) do
        bin.install "agentdash-linux-arm64" => "agentdash"
      end
    end
  end
end
